### ISSUE TITLE
Investigate Batch Effects and Remove Lowly Expressed Genes

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#32]
# Investigate Batch Effects and Remove Lowly Expressed Genes
### DUE: 2021-03-09 @12:00 PM (i.e. Tuesday Meeting)
*deadline may be pushed back depending on when other data preprocessing is completed*

**To-Dos:**
* [x] Merge
* [x] Batch Effects
  * [x] ComBat package
  * [x] Ask Keegan about conversion of units (@FaezeK) 
* [x] Remove lowly expressed genes
  * [x] Remove those with zero
  * [x] Find threshold for removing lowly expressed genes
* [x] Summarize work done (see project-report.md)

**Comment by FaezeK** [comment]
Tried to remove batch effects with limma
<img width="479" alt="Screen Shot 2021-03-30 at 2 37 39 PM" src="https://user-images.githubusercontent.com/11761806/113060557-a885d680-9165-11eb-975b-319a22a10639.png">

Doesn't look very different than ComBat_seq results

**Comment by FaezeK** [comment]
To understand what's the most appropriate approach to remove lowly expressed genes, I was looking at our dataset and was comparing it to the dataset we used in the assignment. So, here are my observations:

Histogram of log10 of raw counts before removing lowly expressed genes (assignment dataset)
<img width="449" alt="Screen Shot 2021-03-30 at 9 19 23 PM" src="https://user-images.githubusercontent.com/11761806/113091930-d5f07580-91a1-11eb-8825-6c95ab3c53d3.png">

Same dataset as above after lowly expressed genes are removed
<img width="453" alt="Screen Shot 2021-03-30 at 9 20 13 PM" src="https://user-images.githubusercontent.com/11761806/113091974-eb659f80-91a1-11eb-8d09-b0e1fc506bc4.png">

Now our colorectal dataset:

Histogram of log10 of raw counts before removing lowly expressed genes (note that genes with expression = 0 across all samples are removed)
<img width="451" alt="Screen Shot 2021-03-30 at 9 16 01 PM" src="https://user-images.githubusercontent.com/11761806/113092063-28ca2d00-91a2-11eb-9994-d10d39efe51a.png">

Same dataset after lowly expressed genes are removed  using edgeR
<img width="453" alt="Screen Shot 2021-03-30 at 9 29 27 PM" src="https://user-images.githubusercontent.com/11761806/113092110-3e3f5700-91a2-11eb-9ee6-e1bf6ade5130.png">

Same dataset after lowly expressed genes are removed using assignment method
<img width="448" alt="Screen Shot 2021-03-30 at 9 33 07 PM" src="https://user-images.githubusercontent.com/11761806/113092160-531bea80-91a2-11eb-9e93-bd0eb37351c2.png">

Based on these graphs, it seemed like we should be able to use even more stringent methods on our dataset to filter genes, so I tried a few other cutoffs including CPM>10 in at least 25% of samples and it's histogram is shown below
<img width="450" alt="Screen Shot 2021-03-30 at 9 38 57 PM" src="https://user-images.githubusercontent.com/11761806/113092325-a2fab180-91a2-11eb-98b0-32b60a644ad7.png">

In the assignment dataset we went from ~58K genes to ~16K genes and here in the very last graph we go from ~20K genes to ~11K genes. I'm thinking maybe filtering genes a bit more might help with our DE analysis, so maybe we should go with CPM>10 in at least 25% of samples?

**Comment by creisle** [comment]
@cmrn-rhi could you try the new genes list/filtering with DE and see how it impacts it? if it doesn't fix the issue then we may not want to change the filtering (since we'd have to re-do the downstream analysis to match). But if it does fix the p-value issue we should go for it!

**Comment by cmrn-rhi** [comment]
Can do between lecture and seminar if someone links me the newly filtered data :)

**Comment by FaezeK** [comment]
I'll share the link shortly in Slack ;)
