### ISSUE TITLE
Survival Analysis

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#36]
# Survival Analysis
### DUE: 2021-03-26
*Rough Deadline*
(Updated: 2021-03-09)

**To-Dos:**

**OR**

- [ ] Survival Analysis with `Censoring`
  - [x] Check: `COX Proportional Hazard Model` depending on covariates
  - [x] PCA to reduce the number of covariates to select features.
  - [x] Check: should dataset be censored?
    - [ ] Low risk group (subtype labeling)
    - [ ] Kaplan-Meier plot(s)
      - [ ] Read paper PMC3105299 mentioned by @clmorrison 

### Keegan Meeting Notes (2021-03-04):

**Then subtype calling and DE analysis**
* ~For Subtyping:~ could use COX proportional hazard model but it carries the fundamental assumption that the hazard at time t is the probability you die at time t - the ratio of hazard to hazard is constant with respect to time.
  * Is that a reasonable assumption? Yes, it's pretty widely used.

**Comment by creisle** [comment]
something we probably should have looked at earlier but.... Just when reading the papers was looking at the sex disparity so I made another KM plot for that

![image](https://user-images.githubusercontent.com/4342641/113625265-913b6300-9615-11eb-97cf-810388f1e379.png)

**Comment by FaezeK** [comment]
Right, very good point. Can you make one based on race or ethnicity too?

**Comment by creisle** [comment]
I don't think we have enough data for that

**Comment by clmorrison** [comment]
@creisle Is the difference statistically significant? If so I can probably add sex to the survival analysis it totally skipped my mind for some reason

**Comment by creisle** [comment]
> @creisle Is the difference statistically significant? If so I can probably add sex to the survival analysis it totally skipped my mind for some reason

I forget how to check that. would you have time to look into it? I am just running out of time on some things

**Comment by clmorrison** [comment]
No problem!

In fact I'm just going to update my code and include sex in the model anyways!

**Comment by clmorrison** [comment]
By the way I included sex as a variable and it didn't really change the resulting analysis. Nonetheless I'm going to add it to my branch and include it in the pull request
