### ISSUE TITLE
DE Analysis

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#37]
# DE Analysis
### DUE: 2021-03-23
*Rough Deadline*

Complete after **Subtype Labels** #9 

**To-Dos:**
- [x] `Limma-voom` analysis (after subtypes are done)
  - [x] Tumour vs Paired Normal DE
  - Subtype DE (DE between subtypes #87)
- [x] Visualize the results using heatmaps
- [ ] Further investigate DE among different metadata groups (e.g. age, sex, race/ethnicity) for these categories

**Comment by cmrn-rhi** [comment]
# DE Troubles - Too Many Significant Genes

**16390/17219** genes are meeting a p-value threshold of 0.5. Keegan agrees that this is unexpected, we wouldn't expect to see this many genes DE, and recommends troubleshooting the steps leading up to this point.

![image](https://user-images.githubusercontent.com/48695054/112522545-0035d380-8d5b-11eb-9bb8-1621d7275072.png)

I'll start by trying to to a DE on the uncorrected Illumina HiSeq data only, since it has both tumor and normal samples, and see if we end up with a similar distribution.

Otherwise Keegan wondered if there might be something going on with the `ComBat_Seq` step since it wasn't provide results similar to the previously run `ComBat` batch correction; however, I mentioned (based on recent readings) that `ComBat_Seq` is less aggressive that regular `ComBat` and wonder if that might be why there are discrepancies.

Otherwise continue to go through the work flow changing one thing at a time to identify the problem.

**Comment by clmorrison** [comment]
Could you provide a histogram of the log p values?

**Comment by cmrn-rhi** [comment]
![image](https://user-images.githubusercontent.com/48695054/112526254-fb731e80-8d5e-11eb-8032-7b5a9a23f65b.png)

**Comment by FaezeK** [comment]
I'm not sure what is happening with the DE analysis, but I added some notes to ComBat vs ComBat_seq question in the progress report issue. It seems like no matter how the batch correction is performed, ComBat_seq doesn't mix data points as vigorous as ComBat.

**Comment by cmrn-rhi** [comment]
Removal of batch effects from DE voom model:

![image](https://user-images.githubusercontent.com/48695054/113066452-6792bf80-916f-11eb-90cd-010217eda1c6.png)

**Comment by cmrn-rhi** [comment]
Results (post-TMM) using newly filtered data:

![image](https://user-images.githubusercontent.com/48695054/113194072-91062680-9215-11eb-9e58-d29c6b7f739c.png)
![image](https://user-images.githubusercontent.com/48695054/113194081-93688080-9215-11eb-995d-fc442c58d661.png)
![image](https://user-images.githubusercontent.com/48695054/113194087-95cada80-9215-11eb-9081-79eb70fd9235.png)
![image](https://user-images.githubusercontent.com/48695054/113194093-97949e00-9215-11eb-8b2d-3d5380b0256b.png)
![image](https://user-images.githubusercontent.com/48695054/113194104-9b282500-9215-11eb-9133-2dcb1ff5c926.png)

**Comment by creisle** [comment]
so we are still seeing a huge number of "significant" DE right? out of curiosity. What happens if you just exclude the GA sequencer data?

**Comment by FaezeK** [comment]
I'll prepare the dataset and post in slack

**Comment by cmrn-rhi** [comment]
### Results (post-TMM) using filtered Hiseq data (`Hiseq_only_low_rmvd.txt`):
![image](https://user-images.githubusercontent.com/48695054/113206340-345e3800-9224-11eb-97c0-118c8d149aed.png)
![image](https://user-images.githubusercontent.com/48695054/113206350-3627fb80-9224-11eb-872d-f746be75204c.png)
![image](https://user-images.githubusercontent.com/48695054/113206360-388a5580-9224-11eb-9c36-d0979c660425.png)
![image](https://user-images.githubusercontent.com/48695054/113206374-3aecaf80-9224-11eb-837d-8d4eea3c475b.png)
![image](https://user-images.githubusercontent.com/48695054/113206380-3d4f0980-9224-11eb-928f-addbe79ac47e.png)

**Comment by cmrn-rhi** [comment]
After looking at all the p.value histograms (non-log10) I think the original data (batch corrected, GA + HiSeq) with the model change (~tumor_status + batch) is the way to go. Not the best, but the best we have.

**Comment by creisle** [comment]
what if we add a fold change (or other minimum change size) filter as well? and limit to only looking at DE genes that fit both that an p-value reqs?

**Comment by cmrn-rhi** [comment]
I'm down to explore filtering by any means.

**Comment by cmrn-rhi** [comment]
So I haven't applied any filters per say, but I have experimented with using `treat()` instead of `eBayes()`: 

> `treat` computes empirical Bayes moderated-t p-values relative to a minimum meaningful fold-change threshold. Instead of testing for genes that have true log-fold-changes different from zero, it tests whether the true log2-fold-change is greater than `lfc` in absolute value (McCarthy and Smyth, 2009). In other words, it uses an interval null hypothesis, where the interval is [-lfc,lfc]. When the number of DE genes is large, `treat` is often useful for giving preference to larger fold-changes and for prioritizing genes that are biologically important. 

I think this makes sense to use with our data but of course want to hear what others think (will post some comparison results below).

**Comment by cmrn-rhi** [comment]
## eBayes vs Treat

### `eBayes`
![image](https://user-images.githubusercontent.com/48695054/113253294-e5db8880-9279-11eb-8668-c20dcd209dd0.png)
![image](https://user-images.githubusercontent.com/48695054/113253340-f2f87780-9279-11eb-9419-5b3e5344d1fb.png)
![image](https://user-images.githubusercontent.com/48695054/113253470-220ee900-927a-11eb-9bda-278013e333aa.png)
![image](https://user-images.githubusercontent.com/48695054/113253512-3357f580-927a-11eb-9f6a-38fd3f2e6ca4.png)
![image](https://user-images.githubusercontent.com/48695054/113253544-3eab2100-927a-11eb-8ed3-81ac384de31d.png)

----
### `treat`
![image](https://user-images.githubusercontent.com/48695054/113253329-effd8700-9279-11eb-81fa-dd0477743a9c.png)
![image](https://user-images.githubusercontent.com/48695054/113253352-f5f36800-9279-11eb-8095-ff0f12d72a3e.png)
![image](https://user-images.githubusercontent.com/48695054/113253486-2804ca00-927a-11eb-8169-28e795428c7a.png)
![image](https://user-images.githubusercontent.com/48695054/113253526-381ca980-927a-11eb-8769-ff2769350fc3.png)
![image](https://user-images.githubusercontent.com/48695054/113253567-41a61180-927a-11eb-865f-6a7ec3d115e5.png)

**Comment by creisle** [comment]
This might be a stupid question but I'm not sure how to use batch in this. For the batch coeff those are genes DE between batches? should we be excluding those from tumour status DE genes?

**Comment by cmrn-rhi** [comment]
The Pheatmap results (z-score) for the top 20 genes by tumor status. Big thanks to @creisle for helping generate the code these results (and integrating the DE work into Snakemake):

![image](https://user-images.githubusercontent.com/48695054/113518354-b1e2ba80-953a-11eb-858c-37423fe59719.png)
![image](https://user-images.githubusercontent.com/48695054/113518360-b7400500-953a-11eb-85a1-7b999c96c956.png)
![image](https://user-images.githubusercontent.com/48695054/113518388-e22a5900-953a-11eb-94c8-c3d83cae4fe1.png)

**Comment by cmrn-rhi** [comment]
## Unpolished Top Gene DE Strip Plots
![image](https://user-images.githubusercontent.com/48695054/113527094-46680f80-9571-11eb-810d-6e78fde985fb.png)
![image](https://user-images.githubusercontent.com/48695054/113527097-4831d300-9571-11eb-81d6-ec6da34b6efa.png)
