### ISSUE TITLE
Identify Genes for Subtype Classification

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#43]
# Identify Genes for Subtype Classification
### DUE: TBD

General to-dos for Aim 3 - can be broken down into smaller tasks once we are reading to address them.

**To-Dos:**
- [ ] Directly compare the fitted regression coefficients of a multinomial logistic regression of subtype classification using RNA expression data.
- [ ] Use multiple imputations to address missing data and determine if any is missing at random.
- [ ] Measure the nature of "missingness" by graphical techniques.
- [ ] Use forward and backward model selection algorithms for optimal classification of genes.
