### ISSUE TITLE
Presentation "Recording"/Practice Run

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#70]
# Presentation "Recording" / Practice Run
### DUE: 2021-**04-06** @ ~1:00PM (i.e. **Tuesday - AFTERNOON**) 
*Presentation will be the following day.*

## To-Do:

- [ ] Zoom/Powerpoint/QuickTime Recording
- [ ] Trim if necessary
- [ ] Determine who will be in charge of playback

## Presentation Criteria:

- [ ] 15 minutes in length
- [ ] All group members should be present (to answer questions at least)
- [ ] Clear sections for content.

**If we don't like the result we consider it a practice run and then just do it live the following day.**
