### ISSUE TITLE
Technical Report - Analysis & Results

### ISSUE THREAD

**Issue by cmrn-rhi** [STAT540-UBC/Repo_team_TeamSix_2021W2#73]
# Technical Report - Analysis & Results
### DUE: 2021-04-09 @12:00 PM (**FRIDAY ~ MIDDAY**)
*Give time for other team members to review if they wish too and to make sure relevant `README.md` is updated*

## **What is this?**
> Think of it as a technical report of your presentation. Add brief comments and text throughout explaining the aim and conclusions of each part. You do not need to talk about all the analysis you have done but make sure you are addressing the important files, such as “inputs” (e.g. the dataset(s) you analyzed) and “outputs” (e.g. plain text files of your key statistical results or PDFs of your main figures)

*Source:* [GitHub Organization Rubric](https://stat540-ubc.github.io/subpages/group_project_rubrics.html#github-repository-10-pts)

## **To-Dos:**
- [ ] Overview of "technical" components of the presentation
  - [ ] Brief comments/text explaining aim and conclusions
  - [ ] Address important files (e.g. all inputs/outputs)
  - Do not need to talk about all of the analysis
- [ ] Finalize as a `.md` report

**Comment by cmrn-rhi** [comment]
Instead of doing an single report, multiple reports were created and mapped to aims within the root README.md

**Comment by FaezeK** [comment]
Sounds great, thanks for doing it
